server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

# Database.
database:
  logger:
    level:   "all"
    stdout:  true

  default:
    link:   "mysql:root:root@tcp(127.0.0.1:3306)/mmdm"
    debug:  true

# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:root@tcp(127.0.0.1:3306)/mmdm"
        tables:          "mmdm_admin,mmdm_datasource,mmdm_datagroup,mmdm_sql_task"
        removePrefix:    "mmdm_"
        descriptionTag:  true
        noModelComment:  true



