// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DatagroupForDao is the golang structure of table mmdm_datagroup for DAO operations like Where/Data.
type Datagroup struct {
	g.Meta      `orm:"dto:true"`
	Id          interface{} // 自增id
	SourceId    interface{} // 数据源id
	Name        interface{} // 组名
	Prefix      interface{} // 组前缀规则
	GroupConfig interface{} // 组命令执行前的sql
	CreateAt    *gtime.Time // 新增时间
	UpdateAt    *gtime.Time // 更新时间
	IsDelete    interface{} // 是否删除
}
