// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mmdm/internal/service/internal/dao/internal"
)

// datagroupDao is the data access object for table mmdm_datagroup.
// You can define custom methods on it to extend its functionality as you wish.
type datagroupDao struct {
	*internal.DatagroupDao
}

var (
	// Datagroup is globally public accessible object for table mmdm_datagroup operations.
	Datagroup = datagroupDao{
		internal.NewDatagroupDao(),
	}
)

// Fill with you ideas below.
