// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mmdm/internal/service/internal/dao/internal"
)

// sqlTaskDao is the data access object for table mmdm_sql_task.
// You can define custom methods on it to extend its functionality as you wish.
type sqlTaskDao struct {
	*internal.SqlTaskDao
}

var (
	// SqlTask is globally public accessible object for table mmdm_sql_task operations.
	SqlTask = sqlTaskDao{
		internal.NewSqlTaskDao(),
	}
)

// Fill with you ideas below.
