// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Admin is the golang structure for table admin.
type Admin struct {
	Id       int64       `json:"id"       description:"自增id"`
	UserName string      `json:"userName" description:"用户名"`
	Salt     string      `json:"salt"     description:"盐"`
	Password string      `json:"password" description:"密码"`
	CreateAt *gtime.Time `json:"createAt" description:"新增时间"`
	UpdateAt *gtime.Time `json:"updateAt" description:"更新时间"`
	IsDelete int         `json:"isDelete" description:"是否删除"`
}
