// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Datasource is the golang structure for table datasource.
type Datasource struct {
	Id       int64       `json:"id"       description:"自增id"`
	Name     string      `json:"name"     description:""`
	Host     string      `json:"host"     description:"host"`
	UserName string      `json:"userName" description:"用户名"`
	Port     int64       `json:"port"     description:"端口"`
	Password string      `json:"password" description:"密码"`
	CreateAt *gtime.Time `json:"createAt" description:"新增时间"`
	UpdateAt *gtime.Time `json:"updateAt" description:"更新时间"`
	IsDelete int         `json:"isDelete" description:"是否删除"`
}
