// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// AdminDao is the data access object for table mmdm_admin.
type AdminDao struct {
	Table   string       // Table is the underlying table name of the DAO.
	Group   string       // Group is the database configuration group name of current DAO.
	Columns AdminColumns // Columns contains all the column names of Table for convenient usage.
}

// AdminColumns defines and stores column names for table mmdm_admin.
type AdminColumns struct {
	Id       string // 自增id
	UserName string // 用户名
	Salt     string // 盐
	Password string // 密码
	CreateAt string // 新增时间
	UpdateAt string // 更新时间
	IsDelete string // 是否删除
}

//  adminColumns holds the columns for table mmdm_admin.
var adminColumns = AdminColumns{
	Id:       "id",
	UserName: "user_name",
	Salt:     "salt",
	Password: "password",
	CreateAt: "create_at",
	UpdateAt: "update_at",
	IsDelete: "is_delete",
}

// NewAdminDao creates and returns a new DAO object for table data access.
func NewAdminDao() *AdminDao {
	return &AdminDao{
		Group:   "default",
		Table:   "mmdm_admin",
		Columns: adminColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AdminDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AdminDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AdminDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
