// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// DatasourceDao is the data access object for table mmdm_datasource.
type DatasourceDao struct {
	Table   string            // Table is the underlying table name of the DAO.
	Group   string            // Group is the database configuration group name of current DAO.
	Columns DatasourceColumns // Columns contains all the column names of Table for convenient usage.
}

// DatasourceColumns defines and stores column names for table mmdm_datasource.
type DatasourceColumns struct {
	Id       string // 自增id
	Name     string //
	Host     string // host
	UserName string // 用户名
	Port     string // 端口
	Password string // 密码
	CreateAt string // 新增时间
	UpdateAt string // 更新时间
	IsDelete string // 是否删除
}

//  datasourceColumns holds the columns for table mmdm_datasource.
var datasourceColumns = DatasourceColumns{
	Id:       "id",
	Name:     "name",
	Host:     "host",
	UserName: "user_name",
	Port:     "port",
	Password: "password",
	CreateAt: "create_at",
	UpdateAt: "update_at",
	IsDelete: "is_delete",
}

// NewDatasourceDao creates and returns a new DAO object for table data access.
func NewDatasourceDao() *DatasourceDao {
	return &DatasourceDao{
		Group:   "default",
		Table:   "mmdm_datasource",
		Columns: datasourceColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *DatasourceDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *DatasourceDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *DatasourceDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
